# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Q_Du1o7htz5GFWr2KBHnCSV8-_FbiFT
"""

pip install pycoingecko pandas plotly

#import the libaries
from pycoingecko import CoinGeckoAPI
import pandas as pd
import plotly.graph_objects as go

#fetching the data
cg = CoinGeckoAPI()

#requesting bitcoin data
bitcoin_data = cg.get_coin_market_chart_by_id(id='bitcoin', vs_currency='usd', days=30)

#extracting relevant data
prices = bitcoin_data['prices']

#converting the data to a panda DataFrame
df = pd.DataFrame(prices, columns=['Date', 'Price'])
df.head()

#converting the UNIX timestamp to a readable date format
df['Date'] = pd.to_datetime(df['Date'], unit='ms')
df.head()

#grouping data to prepare for candlestick plotting
candlestick_data = df.groupby(df['Date'].dt.date).agg({'Price': ['min', 'max', 'first', 'last']})
candlestick_data.head()

candlestick_data.columns = ['min', 'max', 'open', 'close']
candlestick_data.columns

#visualising data with plotly
fig = go.Figure(data=[go.Candlestick(
    x=candlestick_data.index,
    open=candlestick_data['open'],
    high=candlestick_data['max'],
    low=candlestick_data['min'],
    close=candlestick_data['close']
)])

fig.update_layout(
    title='Bitcoin Candlestick Chart for the Last 30 Days',
    xaxis_title='Date',
    yaxis_title='Price (USD)',
)
fig.show()
fig.write_html("bitcoin_candlestick.html")

